name: python

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  basedpyright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run basedpyright
        run: uv run basedpyright **/*.py
